import type { Theme } from "../types/theme";

type StyleKey =
  | "card" | "modal" | "input" | "input-inline"
  | "btn-primary" | "btn-secondary" | "btn-outline" | "btn-icon"
  | "row" | "row-hover" | "checkbox"
  | "border-subtle" | "sidebar-border" | "hover-reveal"
  | "badge" | "btn-export" | "tooltip" | "kbd" | "theme-picker"
  | "page-bg" | "text-heading" | "text-body" | "text-muted" | "text-faint"
  | "accent-text" | "icon-muted" | "icon-hover" | "icon-close-hover"
  | "row-active" | "sidebar-bg" | "sidebar-active" | "sidebar-inactive"
  | "checkbox-checked" | "checkbox-unchecked" | "divider" | "focus-ring"
  | "card-title" | "card-title-muted" | "btn-text" | "hamburger"
  | "search-bar" | "search-highlight";

type StyleMap = Record<StyleKey, string>;

const fancy: StyleMap = {
  "card":              "bg-white rounded-2xl shadow-sm border border-slate-200",
  "modal":             "bg-white rounded-2xl shadow-lg",
  "input":             "bg-slate-50 rounded-xl border border-slate-200",
  "input-inline":      "rounded-lg border border-blue-300",
  "btn-primary":       "bg-blue-500 rounded-xl hover:bg-blue-600 active:bg-blue-700 transition-colors",
  "btn-secondary":     "rounded-xl border border-slate-200 hover:bg-slate-50 transition-colors",
  "btn-outline":       "rounded-xl hover:bg-blue-50 transition-colors",
  "btn-icon":          "transition-colors",
  "row":               "rounded-xl transition-colors",
  "row-hover":         "hover:bg-slate-50",
  "checkbox":          "rounded-lg transition-colors",
  "border-subtle":     "border-slate-200",
  "sidebar-border":    "border-r border-slate-200",
  "hover-reveal":      "opacity-0 group-hover:opacity-100 transition-opacity",
  "badge":             "rounded-full bg-slate-100",
  "btn-export":        "rounded-xl border border-slate-200 hover:bg-white hover:border-slate-300 transition-colors",
  "tooltip":           "rounded-lg bg-slate-800 text-white shadow-lg",
  "kbd":               "rounded bg-slate-600 text-slate-200",
  "theme-picker":      "rounded-xl text-slate-500 hover:text-slate-700 transition-colors",
  "page-bg":           "bg-slate-50",
  "text-heading":      "text-slate-900",
  "text-body":         "text-slate-900",
  "text-muted":        "text-slate-400",
  "text-faint":        "text-slate-300",
  "accent-text":       "text-blue-600",
  "icon-muted":        "text-slate-400",
  "icon-hover":        "hover:text-blue-500",
  "icon-close-hover":  "hover:text-slate-600",
  "row-active":        "border-l-3 border-blue-500 bg-blue-100",
  "sidebar-bg":        "bg-white",
  "sidebar-active":    "bg-blue-50 text-blue-700",
  "sidebar-inactive":  "text-slate-700 hover:bg-slate-100",
  "checkbox-checked":  "bg-blue-500 border-blue-500",
  "checkbox-unchecked": "border-slate-300 hover:border-blue-400",
  "divider":           "divide-slate-100",
  "focus-ring":        "focus:ring-blue-400",
  "card-title":        "text-slate-900",
  "card-title-muted":  "text-slate-500",
  "btn-text":          "text-slate-600",
  "hamburger":         "text-slate-600 hover:text-slate-900 transition-colors",
  "search-bar":        "bg-white rounded-xl shadow-sm border border-slate-200",
  "search-highlight":  "bg-yellow-200/60",
};

const barebones: StyleMap = {
  "card":              "bg-white border border-black",
  "modal":             "bg-white border border-black",
  "input":             "bg-white border border-black",
  "input-inline":      "border border-black",
  "btn-primary":       "bg-blue-600 border border-blue-800",
  "btn-secondary":     "border border-black",
  "btn-outline":       "border border-black hover:bg-blue-50",
  "btn-icon":          "",
  "row":               "",
  "row-hover":         "",
  "checkbox":          "",
  "border-subtle":     "border-black",
  "sidebar-border":    "border-r border-black",
  "hover-reveal":      "",
  "badge":             "border border-black",
  "btn-export":        "border border-black",
  "tooltip":           "border border-black bg-white text-gray-800",
  "kbd":               "border border-black bg-gray-100 text-gray-600",
  "theme-picker":      "border border-black text-gray-600",
  "page-bg":           "bg-white",
  "text-heading":      "text-slate-900",
  "text-body":         "text-slate-900",
  "text-muted":        "text-slate-400",
  "text-faint":        "text-slate-300",
  "accent-text":       "text-blue-600",
  "icon-muted":        "text-slate-400",
  "icon-hover":        "hover:text-blue-500",
  "icon-close-hover":  "hover:text-slate-600",
  "row-active":        "border-l-3 border-blue-500 bg-blue-100",
  "sidebar-bg":        "bg-white",
  "sidebar-active":    "bg-blue-50 text-blue-700",
  "sidebar-inactive":  "text-slate-700",
  "checkbox-checked":  "bg-blue-500 border-blue-500",
  "checkbox-unchecked": "border-slate-300 hover:border-blue-400",
  "divider":           "divide-slate-100",
  "focus-ring":        "focus:ring-blue-400",
  "card-title":        "text-slate-900",
  "card-title-muted":  "text-slate-500",
  "btn-text":          "text-slate-600",
  "hamburger":         "text-slate-600 hover:text-slate-900",
  "search-bar":        "bg-white border border-black",
  "search-highlight":  "bg-yellow-200/60",
};

const vibrant: StyleMap = {
  ...fancy,
  "card":              "bg-white rounded-2xl shadow-md border border-purple-200",
  "modal":             "bg-white rounded-2xl shadow-xl",
  "input":             "bg-purple-50 rounded-xl border border-purple-200",
  "input-inline":      "rounded-lg border border-purple-300",
  "btn-primary":       "bg-gradient-to-r from-purple-500 to-pink-500 rounded-xl hover:from-purple-600 hover:to-pink-600 active:from-purple-700 active:to-pink-700 transition-all",
  "btn-secondary":     "rounded-xl border border-purple-200 hover:bg-purple-50 transition-colors",
  "btn-outline":       "rounded-xl hover:bg-purple-50 transition-colors",
  "row-hover":         "hover:bg-purple-50/50",
  "border-subtle":     "border-purple-200",
  "sidebar-border":    "border-r border-purple-200",
  "badge":             "rounded-full bg-purple-100",
  "btn-export":        "rounded-xl border border-purple-200 hover:bg-white hover:border-purple-300 transition-colors",
  "theme-picker":      "rounded-xl text-purple-500 hover:text-purple-700 transition-colors",
  "page-bg":           "bg-gradient-to-br from-purple-50 via-blue-50 to-pink-50",
  "text-heading":      "text-purple-900",
  "text-body":         "text-purple-900",
  "text-muted":        "text-purple-400",
  "text-faint":        "text-purple-300",
  "accent-text":       "text-purple-600",
  "icon-muted":        "text-purple-400",
  "icon-hover":        "hover:text-purple-500",
  "icon-close-hover":  "hover:text-purple-600",
  "row-active":        "border-l-3 border-purple-500 bg-purple-100",
  "sidebar-active":    "bg-purple-50 text-purple-700",
  "sidebar-inactive":  "text-purple-700 hover:bg-purple-100",
  "checkbox-checked":  "bg-gradient-to-r from-purple-500 to-pink-500 border-purple-500",
  "checkbox-unchecked": "border-purple-300 hover:border-pink-400",
  "divider":           "divide-purple-100",
  "focus-ring":        "focus:ring-purple-400",
  "card-title":        "text-purple-900",
  "card-title-muted":  "text-purple-400",
  "btn-text":          "text-purple-600",
  "hamburger":         "text-purple-600 hover:text-purple-900 transition-colors",
  "search-bar":        "bg-white rounded-xl shadow-sm border border-purple-200",
  "search-highlight":  "bg-pink-200/60",
};

const pastel: StyleMap = {
  ...fancy,
  "card":              "bg-white rounded-2xl shadow-sm border border-violet-200/60",
  "modal":             "bg-white rounded-2xl shadow-lg",
  "input":             "bg-violet-50/50 rounded-xl border border-violet-200/60",
  "input-inline":      "rounded-lg border border-violet-300",
  "btn-primary":       "bg-violet-400 rounded-xl hover:bg-violet-500 active:bg-violet-600 transition-colors",
  "btn-secondary":     "rounded-xl border border-violet-200 hover:bg-violet-50 transition-colors",
  "btn-outline":       "rounded-xl hover:bg-violet-50 transition-colors",
  "row-hover":         "hover:bg-violet-50/40",
  "border-subtle":     "border-violet-200/60",
  "sidebar-border":    "border-r border-violet-200/60",
  "badge":             "rounded-full bg-violet-100/60",
  "btn-export":        "rounded-xl border border-violet-200 hover:bg-white hover:border-violet-300 transition-colors",
  "theme-picker":      "rounded-xl text-violet-400 hover:text-violet-600 transition-colors",
  "page-bg":           "bg-gradient-to-br from-violet-50 via-rose-50 to-emerald-50",
  "text-heading":      "text-violet-900",
  "text-body":         "text-violet-900",
  "text-muted":        "text-violet-400",
  "text-faint":        "text-violet-300",
  "accent-text":       "text-violet-500",
  "icon-muted":        "text-violet-300",
  "icon-hover":        "hover:text-violet-500",
  "icon-close-hover":  "hover:text-violet-600",
  "row-active":        "border-l-3 border-violet-400 bg-violet-100/50",
  "sidebar-active":    "bg-violet-100/50 text-violet-700",
  "sidebar-inactive":  "text-violet-700 hover:bg-violet-50",
  "checkbox-checked":  "bg-violet-400 border-violet-400",
  "checkbox-unchecked": "border-violet-300 hover:border-violet-400",
  "divider":           "divide-violet-100/50",
  "focus-ring":        "focus:ring-violet-300",
  "card-title":        "text-violet-900",
  "card-title-muted":  "text-violet-400",
  "btn-text":          "text-violet-500",
  "hamburger":         "text-violet-500 hover:text-violet-800 transition-colors",
  "search-bar":        "bg-white rounded-xl shadow-sm border border-violet-200/60",
  "search-highlight":  "bg-violet-200/60",
};

const playful: StyleMap = {
  ...fancy,
  "input":             "bg-amber-50 rounded-xl border border-amber-200",
  "input-inline":      "rounded-lg border border-teal-300",
  "btn-primary":       "bg-amber-500 rounded-xl hover:bg-amber-600 active:bg-amber-700 transition-colors",
  "btn-outline":       "rounded-xl hover:bg-teal-50 transition-colors",
  "row-hover":         "hover:bg-teal-50/40",
  "sidebar-border":    "border-r border-teal-200",
  "badge":             "rounded-full bg-amber-100",
  "btn-export":        "rounded-xl border border-teal-200 hover:bg-white hover:border-teal-300 transition-colors",
  "theme-picker":      "rounded-xl text-teal-500 hover:text-teal-700 transition-colors",
  "accent-text":       "text-teal-600",
  "icon-hover":        "hover:text-teal-500",
  "row-active":        "border-l-3 border-teal-500 bg-teal-100",
  "sidebar-bg":        "bg-teal-50",
  "sidebar-active":    "bg-teal-100 text-teal-800",
  "sidebar-inactive":  "text-teal-800 hover:bg-teal-100/60",
  "checkbox-checked":  "bg-purple-500 border-purple-500",
  "checkbox-unchecked": "border-purple-300 hover:border-purple-400",
  "focus-ring":        "focus:ring-teal-400",
  "card-title":        "text-teal-800",
  "card-title-muted":  "text-teal-500",
  "btn-text":          "text-teal-600",
  "hamburger":         "text-teal-600 hover:text-teal-900 transition-colors",
  "search-bar":        "bg-white rounded-xl shadow-sm border border-teal-200",
  "search-highlight":  "bg-amber-200/60",
};

const neon: StyleMap = {
  ...fancy,
  "card":              "bg-slate-800 rounded-2xl shadow-lg shadow-cyan-500/10 border border-slate-700",
  "modal":             "bg-slate-800 rounded-2xl shadow-xl shadow-cyan-500/20",
  "input":             "bg-slate-700 rounded-xl border border-slate-600 text-white placeholder:text-slate-400",
  "input-inline":      "rounded-lg border border-cyan-500/50",
  "btn-primary":       "bg-cyan-500 rounded-xl hover:bg-cyan-400 active:bg-cyan-600 shadow-md shadow-cyan-500/25 transition-all",
  "btn-secondary":     "rounded-xl border border-slate-600 hover:bg-slate-700 transition-colors text-slate-300",
  "btn-outline":       "rounded-xl hover:bg-slate-800 transition-colors",
  "row-hover":         "hover:bg-slate-700/50",
  "border-subtle":     "border-slate-700",
  "sidebar-border":    "border-r border-slate-700",
  "badge":             "rounded-full bg-slate-700",
  "btn-export":        "rounded-xl border border-slate-600 hover:bg-slate-800 hover:border-slate-500 transition-colors",
  "tooltip":           "rounded-lg bg-slate-700 text-cyan-300 shadow-lg shadow-cyan-500/10",
  "kbd":               "rounded bg-slate-600 text-cyan-300",
  "theme-picker":      "rounded-xl text-cyan-400 hover:text-cyan-300 transition-colors",
  "page-bg":           "bg-slate-900",
  "text-heading":      "text-white",
  "text-body":         "text-slate-200",
  "text-muted":        "text-slate-500",
  "text-faint":        "text-slate-600",
  "accent-text":       "text-cyan-400",
  "icon-muted":        "text-slate-500",
  "icon-hover":        "hover:text-cyan-400",
  "icon-close-hover":  "hover:text-white",
  "row-active":        "border-l-3 border-cyan-400 bg-cyan-500/10",
  "sidebar-bg":        "bg-slate-800",
  "sidebar-active":    "bg-cyan-500/10 text-cyan-400",
  "sidebar-inactive":  "text-slate-300 hover:bg-slate-700",
  "checkbox-checked":  "bg-cyan-500 border-cyan-500 shadow-sm shadow-cyan-500/25",
  "checkbox-unchecked": "border-slate-500 hover:border-pink-400",
  "divider":           "divide-slate-700",
  "focus-ring":        "focus:ring-cyan-500",
  "card-title":        "text-white",
  "card-title-muted":  "text-slate-400",
  "btn-text":          "text-cyan-400",
  "hamburger":         "text-cyan-400 hover:text-cyan-300 transition-colors",
  "search-bar":        "bg-slate-700 rounded-xl border border-slate-600",
  "search-highlight":  "bg-cyan-500/30",
};

const themes: Record<Theme, StyleMap> = {
  barebones,
  fancy,
  vibrant,
  pastel,
  playful,
  neon,
};

export function s(theme: Theme, key: StyleKey): string {
  return themes[theme][key];
}
